# Default values for fluent-bit.
# This is a YAML-formatted file.
## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file
config:
  service: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level {{ .Values.logLevel }}
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        Health_Check On

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

    # Node exporter
    [INPUT]
        name            node_exporter_metrics
        tag             node_metrics
        scrape_interval 2

    # Health
    [INPUT]
        Name          health
        Host          peladonerd.com
        Port          443
        tag           peladonerd
        Interval_Sec  10
        Interval_NSec 0

    # Docker events doesn't work in containerd
    # [INPUT]
    #     Name          docker_events

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name            es
        Match           kube.*
        Host            elasticsearch-master
        Logstash_Format On
        Retry_Limit     alse

    [OUTPUT]
        Name            es
        Match           host.*
        Host            elasticsearch-master
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit     False

    # Node exporter
    [OUTPUT]
        name            prometheus_exporter
        match           node_metrics
        host            0.0.0.0
        port            2021

    [OUTPUT]
        Name            es
        Match           peladonerd
        Host            elasticsearch-master

    # [OUTPUT]
    #     Name            es
    #     Match           docker_events
    #     Host            elasticsearch-master

    # [OUTPUT]
    #     Name            slack
    #     Match           peladonerd
    #     webhook         https://hooks.slack.com/services/XXXXXX/XXXXXX/XXXXXXXXX

  ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/upstream-servers
  upstream: {}
#      upstream.conf: |
#        [UPSTREAM]
#            upstream1
#
#        [NODE]
#            name       node-1
#            host       127.0.0.1
#            port       43000

  ## https://docs.fluentbit.io/manual/pipeline/parsers
  customParsers: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

  # This allows adding more files with arbitary filenames to /fluent-bit/etc by providing key/value pairs.
  # The key becomes the filename, the value becomes the file content.
  extraFiles: {}
#     example.conf: |
#       [OUTPUT]
#           Name example
#           Match foo.*
#           Host bar
